CREATE TABLE items(
    id TEXT(10000),
    modId TEXT(10000),
    type TEXT(10000),
    contentType TEXT(10000),
    sandbox TEXT(10000),
    sourceType TEXT(10000),
    sourceId TEXT(10000),
    version TEXT(10000),
    creationDate DATETIME,
    lastModifiedDate DATETIME,
    startDate DATETIME,
    endDate DATETIME,
    isConsumable BOOL,
    isStackable BOOL,
    isTradeable BOOL,
    allowMultipleStacks BOOL,
    isHidden BOOL,
    boostFactor DOUBLE(64, 10),
    creatorId TEXT(10000),
    creatorGamertag TEXT(10000),
    averageRating DOUBLE(64, 10),
    displayProperties TEXT(10000),
    isTest BOOL,
    titleExclusive BOOL,
    PRIMARY KEY(id)
) ENGINE=InnoDB;
